# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-28 20:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('product_desc', models.TextField()),
                ('product_pic', models.FileField(upload_to='products/%Y/%m/%d')),
                ('blog_cate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cat', to='products.Category')),
            ],
        ),
    ]
