# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-28 21:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='blog_cate',
            new_name='product_category',
        ),
    ]
