# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-22 04:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(max_length=100)),
                ('blog_short', models.CharField(max_length=255)),
                ('blog_date', models.DateTimeField()),
                ('blog_content', models.TextField()),
                ('blog_pic', models.ImageField(default='pics/None/no-img.jpg', upload_to='pics/')),
            ],
        ),
    ]
