# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-22 04:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_pic',
            field=models.ImageField(upload_to='/static/'),
        ),
    ]
