# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-22 04:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20161221_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_pic',
            field=models.FileField(upload_to='documents/%Y/%m/%d'),
        ),
    ]
