# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-25 07:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20161223_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_cate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ct', to='blog.Catergories'),
        ),
    ]
